Menu handler
TheDariusz/Simple-TODO-list pull request #8
Opened 2020-11-20 18:51 UTC by TheDariusz

2020-11-21 19:30 UTC, Wertros requested changes
You shouldn't include maven task to this project and instead focus only on menu.
Let's keep this here but for the future it's good not to mix tasks inside single branch.

Consider adding maven wrapper to your project https://www.baeldung.com/maven-wrapper

2020-11-21 19:30 UTC, Wertros commented on src/main/java/pl/coderslab/TaskManager.java
> +    public static final String[] MENU_OPTIONS = {"add", "remove", "list", "exit"};
private

2020-11-21 19:30 UTC, Wertros commented on src/main/java/pl/coderslab/TaskManager.java
> +                if (option.equals(token)){
Why are you so cruel to user and enforce him to put a whole word and even in case sensitive :) Make it easy for him and take only digits input i.e [1-4]

2020-11-21 19:30 UTC, Wertros commented on src/main/java/pl/coderslab/TaskManager.java
> +        return "exit";
please make it static final field

2020-11-22 20:53 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +        Scanner input = new Scanner(System.in);
Scanner with such constructor initialization does not throw an exception:
```
public Scanner(InputStream source)
Constructs a new Scanner that produces values scanned from the specified input stream. Bytes from the stream are converted into characters using the underlying platform's default charset.
Parameters:
source - An input stream to be scanned
```
https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html#Scanner(java.io.InputStream)

2020-11-22 20:56 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
>          String[][] tasks = readTasksFromFile();
Yes, because if I move it to the `switch` part, the file will be read every time when selecting the appropriate options

2020-11-22 20:59 UTC, TheDariusz commented on pom.xml
> +            <version>3.9</version>
corrected

2020-11-22 20:59 UTC, TheDariusz commented on pom.xml
> +                    <target>7</target>
corrected

2020-11-22 21:01 UTC, TheDariusz commented on pom.xml
> +    <artifactId>Simple-TODO-list</artifactId>
corrected

2020-11-22 21:01 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +     */
corrected

2020-11-22 21:02 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +    public static final String[] MENU_OPTIONS = {"add", "remove", "list", "exit"};
corrected

2020-11-22 21:04 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +                if (option.equals(token)){
It was made according to the project requirements

2020-11-22 21:29 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +        return "exit";
the method was completely rebuild

2020-11-24 19:54 UTC, TheDariusz commented on src/main/java/pl/coderslab/TaskManager.java
> +        Scanner input = new Scanner(System.in);
And `Scanner` with `System.in` as argument can be just open because "Since the System.in object is opened by the JVM, you should leave it to the JVM to close it. "

2020-11-24 22:52 UTC, Wertros approved these changes

2020-11-25 18:29 UTC, merged